[package]
name = "procmem_examples"
version = "0.2.0"
authors = ["TheEdward162 <thedward162@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
procmem_access = { path = "../procmem_access" }
procmem_scan = { path = "../procmem_scan" }

anyhow = "1"
rustyline = "11"
