[package]
name = "procmem_access"
version = "0.1.0"
authors = ["TheEdward162 <thedward162@gmail.com>"]
edition = "2021"

[features]
default = ["platform_simple"]
platform_simple = []

[dependencies]
libc = "0.2"
thiserror = "1"

[target.'cfg(target_os="macos")'.dependencies]
mach = "0.3"